tap "homebrew/cask"
tap "homebrew/cask-fonts"

brew "git"
brew "imagemagick"
brew "wpscan"
brew "wget"
brew "python"
brew "macvim"
brew "tmux"
brew "ffmpeg"
brew "reattach-to-user-namespace"
brew "pandoc"
brew "shellcheck"
brew "zsh"
brew "zsh-syntax-highlighting"

# Apps
cask "google-drive-file-stream"
cask "alfred"
cask "bartender"
cask "istat-menus"
cask "1password"
cask "harvest"
cask "spotify"
cask "google-chrome"
cask "zoomus"
cask "slack"
cask "cloudapp"
cask "hazel"
cask "popclip"
cask "backblaze"
cask "sketch"
cask "transmit"
cask "iterm2"
cask "kindlegen"
cask "virtualbox"
cask "daisydisk"
cask "blue-jeans"

# Fonts
cask 'font-lato'
cask 'font-open-sans'
cask 'font-roboto'
cask 'font-roboto-condensed'
cask 'font-source-code-pro-for-powerline'
cask 'font-source-code-pro'
cask 'font-source-sans-pro'
cask 'font-source-serif-pro'
cask 'playfair-display'
cask 'inconsolata'
