# Internal sites

@yourrobotarmy.com:
    ssh: master_gpebuksdac@138.197.192.68 
    path: applications/mbhttfuvzd/public_html/

@admin.robotarmy.industries:
    ssh: master_gpebuksdac@138.197.192.68 
    path: applications/kbzzcnerqt/public_html/

@brettkelly.org:
    ssh: master_gpebuksdac@138.197.192.68 
    path: applications/cukredbfzy/public_html/

@thestronghold.host:
    ssh: master_gpebuksdac@138.197.192.68 
    path: applications/nmkrrszykv/public_html/

@hangonwhat.com:
    ssh: master_gpebuksdac@138.197.192.68 
    path: applications/bmmwmxfzzj/public_html/

@geniusdistillery.com:
    ssh: master_gpebuksdac@138.197.192.68 
    path: applications/sumbezxrrn/public_html/

@lab.robotarmy.industries:
    ssh: master_gpebuksdac@138.197.192.68 
    path: applications/eyntqnwzzq/public_html/

@internal:
    - @yourrobotarmy.com
    - @admin.robotarmy.industries
    - @thestronghold.host
    - @brettkelly.org
    - @hangonwhat.com
    - @geniusdistillery.com
    - @lab.robotarmy.industries


# M&A

@mahl:
    ssh: master_khfrabbytg@45.79.177.82
    path: applications/hucbcngfaj/public_html

@cma:
    ssh: master_khfrabbytg@45.79.177.82
    path: applications/twnqpdafvf/public_html

@tqc:
    ssh: master_khfrabbytg@45.79.177.82
    path: applications/cfdkmehntm/public_html

@manda:
    - @mahl
    - @cma
    - @tqc

# CC

@bmwl:
    ssh: master_hfrgwfwchs@149.28.112.15
    path: applications/jsastksfjs/public_html

@ssim:
    ssh: master_hfrgwfwchs@149.28.112.15
    path: applications/zbqgxdmduy/public_html

@bede:
    ssh: master_hfrgwfwchs@149.28.112.15
    path: applications/htyexyvgjz/public_html

@ptc:
    ssh: master_hfrgwfwchs@149.28.112.15
    path: applications/nssycrwjsr/public_html

@ceecee:
    - @bmwl
    - @ssim
    - @bede
    - @ptc


# Pattern
@logansgapwind.com:
    ssh: bkelly@patternmicro.site
    path: /var/www/microsites/lgw/

